uploads = []

[[generated]]
id = "eVv29MGK93VQaNOeEjLKU"
uri = "file://artifacts/kapsul/assets/images/icon.png"
type = "image"
title = "kapsul app icon"

[[generated]]
id = "iP35SNwuqJo0l1y02uqJd"
uri = "file://artifacts/kapsul/assets/images/mock-photo-1.png"
type = "image"
title = "mock event photo 1"

[[generated]]
id = "3DPBfiA6oetW7tMeL-She"
uri = "file://artifacts/kapsul/assets/images/mock-photo-2.png"
type = "image"
title = "mock event photo 2"

[[generated]]
id = "WoEVPLUfQMYd3yM6U1EkH"
uri = "file://artifacts/kapsul/assets/images/mock-photo-3.png"
type = "image"
title = "mock event photo 3"

[[outputs]]
id = "P4AJh7Zk9yTfVhuxWgec1"
uri = "file://exports/piclo-logo-dark.svg"
type = "image"
title = "piclo-logo-dark.svg — sfondo scuro, testo bianco"

[[outputs]]
id = "Tz75mafS4Y6G9re9vUZRe"
uri = "file://exports/piclo-logo-light.svg"
type = "image"
title = "piclo-logo-light.svg — sfondo bianco, testo scuro"

[[outputs]]
id = "w5lwP9dqTIAgbRISD8r7z"
uri = "file://artifacts/kapsul/assets/images/icon.png"
type = "image"
title = "Piclo App Icon — 1024×1024"
