const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#8B5CF6",
    background: "#08060F",
    foreground: "#FFFFFF",
    card: "#130F1C",
    cardForeground: "#FFFFFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1726",
    secondaryForeground: "#FFFFFF",
    muted: "#1C1726",
    mutedForeground: "#9CA3AF",
    accent: "#EC4899",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D2540",
    input: "#1C1726",
    gradientStart: "#8B5CF6",
    gradientEnd: "#EC4899",
    gradientMid: "#A855F7",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8B5CF6",
    background: "#08060F",
    foreground: "#FFFFFF",
    card: "#130F1C",
    cardForeground: "#FFFFFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1726",
    secondaryForeground: "#FFFFFF",
    muted: "#1C1726",
    mutedForeground: "#9CA3AF",
    accent: "#EC4899",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D2540",
    input: "#1C1726",
    gradientStart: "#8B5CF6",
    gradientEnd: "#EC4899",
    gradientMid: "#A855F7",
  },
  radius: 16,
};

export default colors;
