const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#be123c",
    background: "#08010A",
    foreground: "#FFFFFF",
    card: "#140008",
    cardForeground: "#FFFFFF",
    primary: "#be123c",
    primaryForeground: "#FFFFFF",
    secondary: "#200015",
    secondaryForeground: "#FFFFFF",
    muted: "#200015",
    mutedForeground: "#9CA3AF",
    accent: "#fda4af",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#3D0020",
    input: "#200015",
    gradientStart: "#4c1d95",
    gradientEnd: "#be123c",
    gradientMid: "#881337",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#be123c",
    background: "#08010A",
    foreground: "#FFFFFF",
    card: "#140008",
    cardForeground: "#FFFFFF",
    primary: "#be123c",
    primaryForeground: "#FFFFFF",
    secondary: "#200015",
    secondaryForeground: "#FFFFFF",
    muted: "#200015",
    mutedForeground: "#9CA3AF",
    accent: "#fda4af",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#3D0020",
    input: "#200015",
    gradientStart: "#4c1d95",
    gradientEnd: "#be123c",
    gradientMid: "#881337",
  },
  radius: 16,
};

export default colors;
