// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kapsul-login/CenteredCard.tsx": () => import("../components/mockups/kapsul-login/CenteredCard.tsx"),
  "./components/mockups/kapsul-login/FullBleedDark.tsx": () => import("../components/mockups/kapsul-login/FullBleedDark.tsx"),
  "./components/mockups/kapsul-login/SplitScreen.tsx": () => import("../components/mockups/kapsul-login/SplitScreen.tsx"),
  "./components/mockups/kapsul-palette/Caldo.tsx": () => import("../components/mockups/kapsul-palette/Caldo.tsx"),
  "./components/mockups/kapsul-palette/Lusso.tsx": () => import("../components/mockups/kapsul-palette/Lusso.tsx"),
  "./components/mockups/kapsul-palette/Oceano.tsx": () => import("../components/mockups/kapsul-palette/Oceano.tsx"),
  "./components/mockups/piclo-logos/ArchivoBlack.tsx": () => import("../components/mockups/piclo-logos/ArchivoBlack.tsx"),
  "./components/mockups/piclo-logos/Bold.tsx": () => import("../components/mockups/piclo-logos/Bold.tsx"),
  "./components/mockups/piclo-logos/Condensed.tsx": () => import("../components/mockups/piclo-logos/Condensed.tsx"),
  "./components/mockups/piclo-logos/FredokaChunky.tsx": () => import("../components/mockups/piclo-logos/FredokaChunky.tsx"),
  "./components/mockups/piclo-logos/Gradient.tsx": () => import("../components/mockups/piclo-logos/Gradient.tsx"),
  "./components/mockups/piclo-logos/LilitaOne.tsx": () => import("../components/mockups/piclo-logos/LilitaOne.tsx"),
  "./components/mockups/piclo-logos/Modern.tsx": () => import("../components/mockups/piclo-logos/Modern.tsx"),
  "./components/mockups/piclo-logos/Mono.tsx": () => import("../components/mockups/piclo-logos/Mono.tsx"),
  "./components/mockups/piclo-logos/Neon.tsx": () => import("../components/mockups/piclo-logos/Neon.tsx"),
  "./components/mockups/piclo-logos/NunitoBlack.tsx": () => import("../components/mockups/piclo-logos/NunitoBlack.tsx"),
  "./components/mockups/piclo-logos/Outlined.tsx": () => import("../components/mockups/piclo-logos/Outlined.tsx"),
  "./components/mockups/piclo-logos/PoppinsBlack.tsx": () => import("../components/mockups/piclo-logos/PoppinsBlack.tsx"),
  "./components/mockups/piclo-logos/Script.tsx": () => import("../components/mockups/piclo-logos/Script.tsx"),
  "./components/mockups/piclo-logos/Serif.tsx": () => import("../components/mockups/piclo-logos/Serif.tsx"),
  "./components/mockups/piclo-logos/Slab.tsx": () => import("../components/mockups/piclo-logos/Slab.tsx")
};
