// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kapsul-palette/Caldo.tsx": () => import("../components/mockups/kapsul-palette/Caldo.tsx"),
  "./components/mockups/kapsul-palette/Lusso.tsx": () => import("../components/mockups/kapsul-palette/Lusso.tsx"),
  "./components/mockups/kapsul-palette/Oceano.tsx": () => import("../components/mockups/kapsul-palette/Oceano.tsx")
};
