// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kapsul-login/CenteredCard.tsx": () => import("../components/mockups/kapsul-login/CenteredCard.tsx"),
  "./components/mockups/kapsul-login/FullBleedDark.tsx": () => import("../components/mockups/kapsul-login/FullBleedDark.tsx"),
  "./components/mockups/kapsul-login/SplitScreen.tsx": () => import("../components/mockups/kapsul-login/SplitScreen.tsx"),
  "./components/mockups/kapsul-palette/Caldo.tsx": () => import("../components/mockups/kapsul-palette/Caldo.tsx"),
  "./components/mockups/kapsul-palette/Lusso.tsx": () => import("../components/mockups/kapsul-palette/Lusso.tsx"),
  "./components/mockups/kapsul-palette/Oceano.tsx": () => import("../components/mockups/kapsul-palette/Oceano.tsx")
};
